version: '3'

services:
  redis:
    image: redis:latest
    container_name: ${DATABASE_NETWORK}
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    networks:
      - database
    restart: unless-stopped

  tap:
    container_name: tap
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - database
    ports:
      - ${TORRENT_API_PORT}:${TORRENT_API_PORT}
    build:
      context: .
      dockerfile: ./Dockerfile_tap

  tr_rpc:
    container_name: tr_rpc
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - database
    ports:
      - ${RPC_API_PORT}:${RPC_API_PORT}
    environment:
      - SPIN_PATH=${SPIN_PATH}
      - LOG_LEVEL=${LOG_LEVEL}
      - RPC_API_HOST=${RPC_API_HOST}
      - RPC_API_PORT=${RPC_API_PORT}
      - TRANSMISSION_IP=${TRANSMISSION_IP}
      - TRANSMISSION_PORT=${TRANSMISSION_PORT}
      - TRANSMISSION_USER=${TRANSMISSION_USER}
      - TRANSMISSION_PASS=${TRANSMISSION_PASS}
      - TRANSMISSION_SSHKEY_FILEPATH=${TRANSMISSION_SSHKEY_FILEPATH}
      - VPN_IP=${VPN_IP}
    build:
      context: .
      dockerfile: ./Dockerfile_rpc
      args:
        - SPIN_PATH=${SPIN_PATH}
        - LOG_LEVEL=${LOG_LEVEL}
        - RPC_API_HOST=${RPC_API_HOST}
        - RPC_API_PORT=${RPC_API_PORT}
        - TRANSMISSION_IP=${TRANSMISSION_IP}
        - TRANSMISSION_PORT=${TRANSMISSION_PORT}
        - TRANSMISSION_USER=${TRANSMISSION_USER}
        - TRANSMISSION_PASS=${TRANSMISSION_PASS}
        - TRANSMISSION_SSHKEY_FILEPATH=${TRANSMISSION_SSHKEY_FILEPATH}
        - VPN_IP=${VPN_IP}
      
  spin:
    container_name: spin
    restart: unless-stopped
    depends_on:
      - redis
    security_opt:
      - no-new-privileges:true
    networks:
      - database
    environment:
      - SPIN_PATH=${SPIN_PATH}
      - DOWNLOAD_COVER_IMAGE=${DOWNLOAD_COVER_IMAGE}
      - DATABASE_NETWORK=${DATABASE_NETWORK}
      - REDIS_EXPIRE_SECONDS=${REDIS_EXPIRE_SECONDS}
      - REDIS_IP_ADDR=${REDIS_IP_ADDR}
      - REDIS_PORT=${REDIS_PORT}
      - LOG_LEVEL=${LOG_LEVEL}
      - CRON_SCHEDULE=${CRON_SCHEDULE}
    build:
      context: .
      dockerfile: ./Dockerfile_spin
      args:
        - SPIN_PATH=${SPIN_PATH}
        - DOWNLOAD_COVER_IMAGE=${DOWNLOAD_COVER_IMAGE}
        - DATABASE_NETWORK=${DATABASE_NETWORK}
        - REDIS_EXPIRE_SECONDS=${REDIS_EXPIRE_SECONDS}
        - REDIS_IP_ADDR=${REDIS_IP_ADDR}
        - REDIS_PORT=${REDIS_PORT}
        - LOG_LEVEL=${LOG_LEVEL}
        - CRON_SCHEDULE=${CRON_SCHEDULE}

volumes:
  redis_data:

networks:
  database:
    name: ${DATABASE_NETWORK}
