FROM python:3.12-slim
RUN apt-get update
RUN apt-get install -y ssh curl

WORKDIR /app

ARG SPIN_PATH
ARG LOG_LEVEL
ARG RPC_API_HOST
ARG RPC_API_PORT 
ARG TRANSMISSION_IP
ARG TRANSMISSION_PORT
ARG TRANSMISSION_USER
ARG TRANSMISSION_PASS
ARG TRANSMISSION_SSHKEY_FILEPATH
ARG VPN_IP

COPY requirements_rpc.txt .
COPY $SPIN_PATH/vpn_check.py .
#COPY $SPIN_PATH/__init__.py .
COPY $SPIN_PATH/clogger.py .
COPY $SPIN_PATH/tr_rpc.py .
COPY $SPIN_PATH/main.py .

RUN mkdir -p /app/ssh
COPY ${TRANSMISSION_SSHKEY_FILEPATH} /app/ssh/id_rsa 
RUN chmod 0700 /app/ssh/id_rsa

RUN echo "LOG_LEVEL=$LOG_LEVEL" >> /etc/environment
RUN echo "RPC_API_HOST=$RPC_API_HOST" >> /etc/environment
RUN echo "RPC_API_PORT=$RPC_API_PORT" >> /etc/environment
RUN echo "TRANSMISSION_IP=$TRANSMISSION_IP" >> /etc/environment
RUN echo "TRANSMISSION_PORT=$TRANSMISSION_PORT" >> /etc/environment
RUN echo "TRANSMISSION_USER=$TRANSMISSION_USER" >> /etc/environment
RUN echo "TRANSMISSION_PASS=$TRANSMISSION_PASS" >> /etc/environment
RUN echo "VPN_IP=$VPN_IP" >> /etc/environment

RUN pip3 install -r requirements_rpc.txt

CMD ["python3", "main.py"]

