FROM python:3.12-slim
RUN apt-get update && apt-get install -y git

RUN git clone https://github.com/Ryuk-me/Torrent-Api-py
RUN pip3 install -r Torrent-Api-py/requirements.txt

CMD ["python3", "Torrent-Api-py/main.py"]

